dist: bionic
language: go
go:
  - "1.13.x"

install:
  - sudo apt-get install -y zfsutils-linux && sudo modprobe zfs
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/kunalkushwaha/ltag

before_script:
  - pushd ..; git clone https://github.com/containerd/project; popd

script:
  - DCO_VERBOSITY=-q ../project/script/validate/dco
  - ../project/script/validate/fileheader ../project/
  - go test -race -covermode=atomic -c .
  - sudo ./zfs.test -test.root -test.v -test.coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
