dist: trusty
sudo: required
language: go
go:
  - 1.8.x
go_import_path: github.com/AkihiroSuda/containerd-zfs
install:
  - sudo apt-add-repository -y ppa:zfs-native/stable && sudo apt-get update && sudo apt-get -y install linux-headers-$(uname -r) && sudo apt-get -y install ubuntu-zfs && sudo modprobe zfs
  - expected_containerd_commit=$(make echo-expected-containerd-commit)
  - mkdir -p $GOPATH/src/github.com/containerd && cd $GOPATH/src/github.com/containerd && git clone https://github.com/containerd/containerd.git && cd containerd && git checkout ${expected_containerd_commit}
  - cd $GOPATH/src/github.com/AkihiroSuda/containerd-zfs
script:
  - make
  - sudo make test
